/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerArquivoTextoCliente;
import Model.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Galhardo
 */
public class CadCliente extends javax.swing.JFrame {
    
    int indice = 0;
    ControllerArquivoTextoCliente controler = new ControllerArquivoTextoCliente();
    private static CadCliente cadClienteUnico;
    Cliente clienteaux;

    /**
     * Creates new form CadCliente
     */
    public CadCliente() {
        initComponents();
    }
    // Inicio Singleton
    public static CadCliente getCadCliente(){
        if(cadClienteUnico == null){
            cadClienteUnico = new CadCliente();
        }
        return cadClienteUnico;
    }
    //Fiim Singleton

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        butAbrir = new javax.swing.JButton();
        butSalvar = new javax.swing.JButton();
        butProx = new javax.swing.JButton();
        butAnterior = new javax.swing.JButton();
        butSair = new javax.swing.JButton();
        butLimpar = new javax.swing.JButton();
        butExcluir = new javax.swing.JButton();
        butAlterar = new javax.swing.JButton();
        lblCons = new javax.swing.JLabel();
        txtCons = new javax.swing.JTextField();
        butCons = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("CADASTRO DE CLIENTE");

        lblNome.setText("NOME");

        lblCpf.setText("CPF");

        lblEmail.setText("EMAIL");

        lblContato.setText("CONTATO");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        lblRg.setText("RG");

        butAbrir.setText("ABRIR");
        butAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAbrirActionPerformed(evt);
            }
        });

        butSalvar.setText("SALVAR");
        butSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalvarActionPerformed(evt);
            }
        });

        butProx.setText("PROXIMO");
        butProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butProxActionPerformed(evt);
            }
        });

        butAnterior.setText("ANTERIOR");
        butAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnteriorActionPerformed(evt);
            }
        });

        butSair.setText("SAIR");
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        butLimpar.setText("LIMPAR");
        butLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimparActionPerformed(evt);
            }
        });

        butExcluir.setText("EXCLUIR");
        butExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcluirActionPerformed(evt);
            }
        });

        butAlterar.setText("ALTERAR");
        butAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAlterarActionPerformed(evt);
            }
        });

        lblCons.setText("PESQUISAR");

        txtCons.setText("Digite o cpf...");

        butCons.setText("CONSULTAR");
        butCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butAbrir)
                        .addGap(48, 48, 48)
                        .addComponent(butExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAlterar)
                        .addGap(40, 40, 40)
                        .addComponent(butSalvar)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addGap(27, 27, 27)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRg))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContato))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(butLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butAnterior)
                                .addGap(18, 18, 18)
                                .addComponent(butProx)
                                .addGap(11, 11, 11)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butCons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(butSair))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCons)
                    .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpf)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRg)
                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContato)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butProx, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSalvar)
                    .addComponent(butAbrir)
                    .addComponent(butExcluir)
                    .addComponent(butAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void butAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnteriorActionPerformed
       Navega(--indice);
    }//GEN-LAST:event_butAnteriorActionPerformed

    private void butSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalvarActionPerformed
        controler.setArquivo("salvar");
        Cliente cli = new Cliente();
        cli.setNome(txtNome.getText());
        cli.setCpf(txtCpf.getText());
        cli.setRg(txtRg.getText());
        cli.setEmail(txtEmail.getText());
        cli.setContato(txtContato.getText());
        controler.getClientes().add(cli);
        try {
            controler.escreverCliente(true);
            JOptionPane.showMessageDialog(null, "ARQUIVO SALVO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO SALVAR O ARQUIVO!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_butSalvarActionPerformed

    private void butAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAbrirActionPerformed
        controler.setArquivo("Abrir");
        controler.lerCliente();
        indice = 0;
        Navega(indice);
    }//GEN-LAST:event_butAbrirActionPerformed

    private void butProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butProxActionPerformed
       Navega(++indice);
    }//GEN-LAST:event_butProxActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        sair();
    }//GEN-LAST:event_butSairActionPerformed

    private void butLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimparActionPerformed
       limpaCampos();
    }//GEN-LAST:event_butLimparActionPerformed

    private void butExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcluirActionPerformed
    
     
        try {
            Cliente cli = controler.getClientes().get(indice);
            controler.removeElemento(cli);

            // Atualiza os índices dos próximos elementos
            for (int i = indice; i < controler.getClientes().size(); i++) {
                controler.getClientes().get(i);
            }

            controler.escreverCliente(true);

            limpaCampos();
            JOptionPane.showMessageDialog(null, "CLIENTE EXCLUÍDO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO EXCLUIR O CLIENTE!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_butExcluirActionPerformed

    private void butAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAlterarActionPerformed
        
          try {
            clienteaux.setNome(txtNome.getText());
            clienteaux.setCpf(txtCpf.getText());
            clienteaux.setRg(txtRg.getText());
            clienteaux.setEmail(txtEmail.getText());
            clienteaux.setContato(txtContato.getText());
            
            controler.atualizaCliente(clienteaux);
            
            JOptionPane.showMessageDialog(null, "CLIENTE ALTERADO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO ALTERAR O CLIENTE!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butAlterarActionPerformed

    private void butConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConsActionPerformed
        Cliente cli = new Cliente();
        cli.setCpf(txtCons.getText());

        Cliente clienteConsultado = controler.consCliente(cli);

        if (clienteConsultado != null) {

            txtNome.setText(clienteConsultado.getNome());
            txtCpf.setText(clienteConsultado.getCpf());
            txtRg.setText(clienteConsultado.getRg());
            txtEmail.setText(clienteConsultado.getEmail());
            txtContato.setText(clienteConsultado.getContato());
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "CPF NAO ENCONTRADO!",
                    "ERRO CONSULTA",
                    JOptionPane.ERROR_MESSAGE
            );
        }
      
    }//GEN-LAST:event_butConsActionPerformed

    public void Navega(int indice) {

        ArrayList<Cliente> cliente = controler.getClientes();

        if (indice >= 0 && indice < cliente.size()) {
            Cliente cli = controler.getClientes().get(indice);
            cli.setInd(indice);
            clienteaux = cli;
            txtNome.setText(cli.getNome());
            txtCpf.setText(cli.getCpf());
            txtRg.setText(cli.getRg());
            txtEmail.setText(cli.getEmail());
            txtContato.setText(cli.getContato());
        } else {
            JOptionPane.showMessageDialog(null, "INDICE INVÁLIDO \nTODOS CLIENTES PERCORRIDOS");

        }

    }

    public void limpaCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtRg.setText("");
        txtEmail.setText("");
        txtContato.setText("");
        txtCons.setText("");
    }
    
    public void sair(){
        int respSair = JOptionPane.showConfirmDialog(
                    null,
                    "DESEJA REALMENTE SAIR?",
                    "SAIR",
                    JOptionPane.YES_NO_OPTION
            );
        
        if(respSair == 0){
            dispose();
        }
    }

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAbrir;
    private javax.swing.JButton butAlterar;
    private javax.swing.JButton butAnterior;
    private javax.swing.JButton butCons;
    private javax.swing.JButton butExcluir;
    private javax.swing.JButton butLimpar;
    private javax.swing.JButton butProx;
    private javax.swing.JButton butSair;
    private javax.swing.JButton butSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCons;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    // End of variables declaration//GEN-END:variables
}
