/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerArquivoTextoFornecedor;
import Model.Fornecedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Galhardo
 */
public class CadForn extends javax.swing.JFrame {
    
    int indice = 0;
    ControllerArquivoTextoFornecedor controler = new ControllerArquivoTextoFornecedor();
    private static CadForn cadFornUnico;
    Fornecedor fornaux;

    /**
     * Creates new form CadForn
     */
    public CadForn() {
        initComponents();
    }
    
    // Inicio Singleton
    public static CadForn getCadForn(){
        if(cadFornUnico == null){
            cadFornUnico = new CadForn();
        }
        return cadFornUnico;
    }
    //Fiim Singleton

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblInsEst = new javax.swing.JLabel();
        txtInsEst = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblRazao = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        butAlterar = new javax.swing.JButton();
        butAbrir = new javax.swing.JButton();
        butSalvar = new javax.swing.JButton();
        butProx = new javax.swing.JButton();
        butAnterior = new javax.swing.JButton();
        butLimpar = new javax.swing.JButton();
        butExcluir = new javax.swing.JButton();
        lblCons = new javax.swing.JLabel();
        txtCons = new javax.swing.JTextField();
        butCons = new javax.swing.JButton();
        butSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("CADASTRO FORNECEDORES");

        lblInsEst.setText("INSC. EST");

        lblRazao.setText("RAZAO SOCIAL");

        lblCnpj.setText("CNPJ");

        lblEmail.setText("EMAIL");

        lblContato.setText("CONTATO");

        txtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjActionPerformed(evt);
            }
        });

        butAlterar.setText("ALTERAR");
        butAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAlterarActionPerformed(evt);
            }
        });

        butAbrir.setText("ABRIR");
        butAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAbrirActionPerformed(evt);
            }
        });

        butSalvar.setText("SALVAR");
        butSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalvarActionPerformed(evt);
            }
        });

        butProx.setText("PROXIMO");
        butProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butProxActionPerformed(evt);
            }
        });

        butAnterior.setText("ANTERIOR");
        butAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnteriorActionPerformed(evt);
            }
        });

        butLimpar.setText("LIMPAR");
        butLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimparActionPerformed(evt);
            }
        });

        butExcluir.setText("EXCLUIR");
        butExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcluirActionPerformed(evt);
            }
        });

        lblCons.setText("PESQUISAR");

        txtCons.setText("Digite o cnpj...");

        butCons.setText("CONSULTAR");
        butCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConsActionPerformed(evt);
            }
        });

        butSair.setText("SAIR");
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRazao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRazao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCnpj)
                        .addGap(27, 27, 27)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblInsEst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsEst, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butAbrir)
                        .addGap(48, 48, 48)
                        .addComponent(butExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAlterar)
                        .addGap(40, 40, 40)
                        .addComponent(butSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(butProx))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butCons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(butSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCons)
                    .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCons))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazao)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCnpj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInsEst)
                        .addComponent(txtInsEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContato)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butProx, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSalvar)
                    .addComponent(butAbrir)
                    .addComponent(butExcluir)
                    .addComponent(butAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjActionPerformed

    private void butAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAlterarActionPerformed

        try {
            fornaux.setRazaoSocial(txtRazao.getText());
            fornaux.setCnpj(txtCnpj.getText());
            fornaux.setInscEst(txtInsEst.getText());
            fornaux.setEmail(txtEmail.getText());
            fornaux.setContato(txtContato.getText());

            controler.atualizaForn(fornaux);

            JOptionPane.showMessageDialog(null, "FORNECEDOR ALTERADO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO ALTERAR O FORNECEDOR!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butAlterarActionPerformed

    private void butAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAbrirActionPerformed
        controler.setArquivo("Abrir");
        controler.lerFornecedor();
        indice = 0;
        Navega(indice);
    }//GEN-LAST:event_butAbrirActionPerformed

    private void butSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalvarActionPerformed
        controler.setArquivo("salvar");
        Fornecedor forn = new Fornecedor();
        forn.setRazaoSocial(txtRazao.getText());
        forn.setCnpj(txtCnpj.getText());
        forn.setInscEst(txtInsEst.getText());
        forn.setEmail(txtEmail.getText());
        forn.setContato(txtContato.getText());
        controler.getFornes().add(forn);
        try {
            controler.escreverFornecedor(true);
            JOptionPane.showMessageDialog(null, "ARQUIVO SALVO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO SALVAR O ARQUIVO!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butSalvarActionPerformed

    private void butProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butProxActionPerformed
        Navega(++indice);
    }//GEN-LAST:event_butProxActionPerformed

    private void butAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnteriorActionPerformed
        Navega(--indice);
    }//GEN-LAST:event_butAnteriorActionPerformed

    private void butLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_butLimparActionPerformed

    private void butExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcluirActionPerformed

        try {
            Fornecedor forn = controler.getFornes().get(indice);
            controler.removeElemento(forn);

            // Atualiza os índices dos próximos elementos
            for (int i = indice; i < controler.getFornes().size(); i++) {
                controler.getFornes().get(i);
            }

            controler.escreverFornecedor(true);

            limpaCampos();
            JOptionPane.showMessageDialog(null, "FORNECEDOR EXCLUÍDO COM SUCESSO!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO EXCLUIR O FORNECEDOR!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butExcluirActionPerformed

    private void butConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConsActionPerformed
        Fornecedor forn = new Fornecedor();
        forn.setCnpj(txtCons.getText());

        Fornecedor fornConsultado = controler.consForn(forn);

        if (fornConsultado != null) {

            txtRazao.setText(fornConsultado.getRazaoSocial());
            txtCnpj.setText(fornConsultado.getCnpj());
            txtInsEst.setText(fornConsultado.getInscEst());
            txtEmail.setText(fornConsultado.getEmail());
            txtContato.setText(fornConsultado.getContato());
        } else {
            JOptionPane.showMessageDialog(
                null,
                "CNPJ NAO ENCONTRADO!",
                "ERRO CONSULTA",
                JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_butConsActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        sair();
    }//GEN-LAST:event_butSairActionPerformed

     public void Navega(int indice) {

        ArrayList<Fornecedor> fornecedor = controler.getFornes();

        if (indice >= 0 && indice < fornecedor.size()) {
            Fornecedor forn = controler.getFornes().get(indice);
            forn.setInd(indice);
            fornaux = forn;
            txtRazao.setText(forn.getRazaoSocial());
            txtCnpj.setText(forn.getCnpj());
            txtInsEst.setText(forn.getInscEst());
            txtEmail.setText(forn.getEmail());
            txtContato.setText(forn.getContato());
        } else {
            JOptionPane.showMessageDialog(null, "INDICE INVÁLIDO \nTODOS FORNECEDORES PERCORRIDOS");

        }

    }
     public void sair(){
        int respSair = JOptionPane.showConfirmDialog(
                    null,
                    "DESEJA REALMENTE SAIR?",
                    "SAIR",
                    JOptionPane.YES_NO_OPTION
            );
        
        if(respSair == 0){
            dispose();
        }
    }
     
    
    public void limpaCampos() {
        txtRazao.setText("");
        txtCnpj.setText("");
        txtInsEst.setText("");
        txtEmail.setText("");
        txtContato.setText("");
    }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAbrir;
    private javax.swing.JButton butAlterar;
    private javax.swing.JButton butAnterior;
    private javax.swing.JButton butCons;
    private javax.swing.JButton butExcluir;
    private javax.swing.JButton butLimpar;
    private javax.swing.JButton butProx;
    private javax.swing.JButton butSair;
    private javax.swing.JButton butSalvar;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCons;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInsEst;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInsEst;
    private javax.swing.JTextField txtRazao;
    // End of variables declaration//GEN-END:variables
}
